{% set version = "1.0.7" %}

package:
  name: pytest-nunit
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-nunit/pytest-nunit-{{ version }}.tar.gz
  sha256: 29cd259b847510d751c971af987a15dcbb843ec2d076dd03f31cac7a848bed90

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - attrs
    - pytest >=4.6.0
    - python

test:
  imports:
    - pytest_nunit
    - pytest_nunit.models
  requires:
    - pip
    - python
  commands:
    - pip check

about:
  home: https://pypi.org/project/pytest-nunit
  dev_url: https://github.com/pytest-dev/pytest-nunit
  doc_source_url: https://github.com/pytest-dev/pytest-nunit
  description: A pytest plugin for generating NUnit3 test result XML output
  summary: A pytest plugin for generating NUnit3 test result XML output
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - tonybaloney
