{% set version = "1.0.6" %}

package:
  name: pytest-nunit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-nunit/pytest-nunit-{{ version }}.tar.gz
  sha256: e967b44465af7203873c652a89ef3b114d7d3bb01085b80773050609f63d3053

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs
    - pytest >=4.6.0
    - python >=3.6

test:
  imports:
    - pytest_nunit
    - pytest_nunit.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-nunit
  summary: A pytest plugin for generating NUnit3 test result XML output
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - tonybaloney
