{% set name = "pytest-nunit" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c3e7a5396d0c3910c043d2d9aa4085777b21183d993e09b24411efb276aa10b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python
  run:
    - attrs
    - pytest >=3.5.0
    - python

test:
  imports:
    - pytest_nunit
    - pytest_nunit.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-nunit
  summary: A pytest plugin for generating NUnit3 test result XML output
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
